TLS Client authentication
AdguardTeam/dnsproxy pull request #172
Opened 2021-10-05 11:42 UTC by MarinoMtz

Hello I added support for TLS Authentication. For now I tested it with my own DoH server and open ssl certificates. It should also work for DoT and DoQ but need further tested.

I tried my best to follow the comments from @ameshkov in my previous pull request (doauth).

BR
Ivan

2021-10-07 08:48 UTC, ameshkov requested changes
Please read all comments before making changes.

Briefly:

1. Instead of `TLSClientConfig` we should pass `TLSClientCertificates` down to the upstreams. Passing the whole config seems unnecessary.
2. There are some naming inconsistencies that should be resolved.
3. There are no unit tests at all for this feature.

How to write a unit test. The tests that we have in the `upstream` right now are not ideal since they depend on remote servers.

For this feature, we'd better write a normal unit test that does not have any external dependencies.

Let's start with a DOT server. Here's what needs to be done:

1. Generate a server cert-key pair (see `createServerTLSConfig` in `proxy_test.go`)
2. Generate a client cert-key pair.
3. Create a `net.Listener` that listens to `127.0.0.1:0` (this way it will use an unoccupied port)
4. Grab the port from listener.Addr(), you'll use it to create an upstream
5. Create a `tls.Listener` with the tls.Config from steps 1 and 2. This tls.Config should have the following fields set:
    * `Certificates`, `ClientAuth` and `ClientCAs` -- so that it was verifying the client cert. See the example here: https://gist.github.com/xjdrew/97be3811966c8300b724deabc10e38e2#file-server-go-L29
6. This tls.Listener should accept the incoming connection, read the DNS message, check that it's valid and return some response.
7. Create an Upstream with `InsecureSkipVerify` set to true and TLS client auth enabled.
8. Send a DNS message through it and verify the response.

One thing to note. Instead of setting `InsecureSkipVerify` on step 6 it might be better to have an option to pass `RootCAs` to the the upstream's TLS config. Currently, it can be done via `upstream.RootCAs` property, but tbh this is a part of the old code that is not used anymore and can be removed. Consider extending `upstream.Options` and allowing passing `RootCAs` via it.

2021-10-07 08:48 UTC, ameshkov commented on README.md
> +> Note that `DoH/DoT/DoQ` client authentication support is experimental, only DoH authentication has been tested
Why? We can test this rather easily with a unit-test for all three

2021-10-07 08:48 UTC, ameshkov commented on README.md
> +      --a-tls-crt=       Path to the file to the tls certificate used to DoH/DoT/DoQ Client when client-authentication is enabled
Let's rename it to `tls-client-crt` and `tls-client-key`

2021-10-07 08:48 UTC, ameshkov commented on README.md
> +      --a-tls-crt=       Path to the file to the tls certificate used to DoH/DoT/DoQ Client when client-authentication is enabled
The comment:
```
Path to the file with the TLS certificate used for TLS client authentication (supported by DoH/DoT/DoQ).
```

2021-10-07 08:48 UTC, ameshkov commented on main.go
> +var tlsclient = false
Uh, I really don't like passing arguments via global variables. Please refactor the code so that this wasn't necessary.

2021-10-07 08:48 UTC, ameshkov commented on main.go
> +	cert, err := loadX509KeyPair("", "")
This looks very strange

2021-10-07 08:48 UTC, ameshkov commented on main.go
> +	if options.TLSAuthCertPath != "" {
Tbh, I don't like how it's done. It would be clearer if we had two different functions for that:

`newTLSConfig`
`newTLSAuthConfig`

And a third function that sets TLS options `setTLSOptions` where you can move max/min versions logic.

2021-10-07 08:48 UTC, ameshkov commented on upstream/bootstrap.go
> +			Certificates: n.options.TLSClientConfig.Clone().Certificates,
Wouldn't it be enough to just use the `tlsConfig` defined above and set `Certificates` there instead of creating a new one?

2021-10-07 08:48 UTC, ameshkov commented on proxy/config.go
> +	TLSClientConfig      *tls.Config    // necessary for DoH/DoT/DoQ Client Authentication
There's some inconsistency in the naming.

In `main.go` it's TLSAuth, here it is TLSClient.

Let's choose a single prefix and use it everywhere. IMO, both are okay, we just need it to be consistent

2021-10-07 08:48 UTC, ameshkov commented on upstream/upstream.go
> +	TLSClient bool // TLS client authentication flag when DoH/DoT/DoQ Client Authentication is used
I don't think we need this field. The fact that the client certificates have been configured already signals us that the TLS client auth is enabled.

2021-10-07 08:48 UTC, ameshkov commented on upstream/upstream.go
> +
Unnecessary empty line

2021-10-07 08:48 UTC, ameshkov commented on upstream/upstream.go
> +	TLSClientConfig *tls.Config // TLS config when DoH/DoT/DoQ Client Authentication is used
I've looked at the code and it seems that we're using only the `Certificates` field from this config.

So here's the question: do we **really** need the whole TLS config here? Can we instead pass just the certificates?

2021-10-07 08:48 UTC, ameshkov commented on upstream/bootstrap_resolver.go
> +
Unnecessary empty line

2022-03-14 03:24 UTC, GAMEZs9 approved these changes

2026-04-27 12:31 UTC, closed without merging