add support for hyphen separated wildcard domains
AdguardTeam/dnsproxy pull request #246
Opened 2022-07-22 17:30 UTC by marriva

Hello!

Please add support for wildcards separated by hyphen, for example, `*-dev.example.org` and `*-prod.example.org`

I need to use different upstreams for `something-dev.example.org` and `something-prod.example.org`

2022-08-01 08:50 UTC, ameshkov requested changes
Hi, thank you for the contribution!

Could you please also add unit-tests for that?

Sample configurations for the test:
```
conf := []string{
		"0.0.0.1",
		"[/a.x/]0.0.0.2",
		"[/*-b.a.x/]0.0.0.3",
		"[/b.a.x/]0.0.0.4",
		"[/*-c.b.a.x/]0.0.0.5",
		"[/c.b.a.x/]#",
	}
```

```
conf := []string{
		"0.0.0.1",
		"[/a.x/]0.0.0.2",
		"[/*.a.x/]0.0.0.3",
		"[/*-b.a.x/]0.0.0.4",
		"[/b.a.x/]0.0.0.5",
	}
```

```
"[/*-a.b.c/]0.0.0.1", 
"[/*-.b.c/]0.0.0.2", 
"[/*.b-x.c/]0.0.0.3"
```

2022-08-04 16:15 UTC, EugeneOne1 commented
@marriva, hello.  The unbound documentation states:
 >  Matching of domains is normally done on complete labels, so /google.com/ matches google.com and www.google.com but NOT supergoogle.com. This can be overridden with a * at the start of a pattern only: /*google.com/ will match google.com and www.google.com AND supergoogle.com. The non-wildcard form has priority, so if /google.com/ and /*google.com/ are both specified then google.com and www.google.com will match /google.com/ and /*google.com/ will only match supergoogle.com.
 >  For historical reasons, the pattern /.google.com/ is equivalent to /google.com/ if you wish to match any subdomain of google.com but NOT google.com itself, use /*.google.com/

AFAIK, it doesn't apply any special handling for domains (and patterns) with hyphens.  As per the man page, Dnsmasq supports the following wildcard pattern types:

 *  `domain.tld` – matching both `domain.tld` and `*.domain.tld` (supported by dnsproxy);
 *  `*.domain.tld` – matching only subdomains of `domain.tld` (supported by dnsproxy);
 *  `*domain.tld` – matching `domain.tld` itself and any name having suffix of `domain.tld`.

Thus the PR seems a bit incomplete in terms of adding support for the last pattern type since it only handles the `*-domain.tld` case.  If we'll accept this, it may be complicated to implement the rest of the logic afterwards so I believe it should be done at once.

@ameshkov, what do you think?

2022-10-28 14:28 UTC, Nuttapon-Makchoos approved these changes
@marriva

2022-10-28 14:29 UTC, Nuttapon-Makchoos reviewed
@marriva

2022-10-28 14:30 UTC, Nuttapon-Makchoos reviewed
#284

2026-04-28 12:21 UTC, closed without merging